/**
 * The app icon, on the web.
 *
 * The phone has had this icon for a while and the website did not: the tab
 * showed the pale mark on white — the *other* drawing, the one `Mark.tsx`
 * renders inline on a page — so the thing on somebody's home screen and the
 * thing in their tab strip were two different logos. `brand.test.ts` had the
 * split written down as a deliberate deferral, with the note that carrying the
 * dark icon across "wants deciding on its own". This is that decision, taken
 * for the two surfaces where the product appears as an *icon* rather than as a
 * mark on a page: the favicon, and the picture on a shared link.
 *
 * Deliberately not the pages. `Mark` still draws the pale version inline on the
 * sign-in card and over an empty thread, because those sit on a white page at
 * 22 to 48px, where this one would have to arrive as a badge — a saturated
 * square with corners, in the middle of a sheet of white. That is a change to
 * every screen the mark appears on and it is still not this one.
 *
 * ## Why the numbers are here twice
 *
 * The master is `assets/branding/parea-icon-dark-refined.svg`, generated by
 * `scripts/build-icon.mjs` from three numbers and rendered into the app's store
 * assets by `apps/mobile/scripts/render-icons.mjs`. A server route cannot read
 * it: it is outside `apps/web`, and what a function gets in a deployment is
 * what the bundler traced, not what is in the repository.
 *
 * So it is mirrored, and `brand.test.ts` compares `appIconSvg()` against the
 * master with whitespace normalised. That is the arrangement this codebase
 * already runs for the mark in five places, and the reason is the same one: an
 * unchecked copy is how the link-preview image came to have a palette of its
 * own that nobody noticed for months.
 */

/** Under everything, and not white: white showing through where no bloom
    reaches full strength reads as a vignette rather than as air. */
export const FIELD_BASE = '#173EA8';

/**
 * Five blooms and a seam, each `[id, cx, cy, r, stops]` in the 1024 grid.
 *
 * Rose at the top, violet top left, blue down the left, aqua at the foot, teal
 * at the right — and `gradSeam`, which is `gradPurple`'s own second colour
 * placed where the rose hands over to the teal. Those two are 170° apart and
 * alpha compositing averages them toward grey; a colour that sits between them
 * on the wheel takes the handover the short way round. See the master for the
 * measurements that settled it.
 */
export const GRADIENTS: [string, number, number, number, [number, string, number][]][] = [
  ['gradPink', 700, 40, 820, [
    [0, '#F79AB6', 1], [34, '#EB78A0', 0.92], [68, '#D86196', 0.42], [100, '#D86196', 0],
  ]],
  ['gradPurple', 130, 170, 620, [
    [0, '#8F46DA', 0.78], [36, '#7B39C8', 0.5], [72, '#6E35BE', 0.12], [100, '#6E35BE', 0],
  ]],
  ['gradBlue', 80, 780, 780, [
    [0, '#1337B7', 1], [36, '#1945C6', 0.96], [70, '#1D49C9', 0.42], [100, '#1D49C9', 0],
  ]],
  ['gradCyan', 520, 1040, 560, [
    [0, '#25BCE6', 0.92], [38, '#21AEDD', 0.68], [72, '#1E9FD5', 0.18], [100, '#1E9FD5', 0],
  ]],
  ['gradSeam', 1010, 330, 640, [
    [0, '#7D37CC', 0.62], [45, '#7D37CC', 0.5], [86, '#7D37CC', 0],
  ]],
  ['gradTeal', 1030, 760, 760, [
    [0, '#66E7C6', 0.95], [34, '#46D8C1', 0.84], [70, '#39CDBD', 0.34], [100, '#39CDBD', 0],
  ]],
];

/**
 * The mark's own geometry: three circles 132 from a point, 120° apart, first
 * one straight up, at a radius of 182.
 *
 * The centre they sit around is 16.5 below the canvas middle — the mark is
 * placed between the two defensible centrings rather than on its mass, which
 * is the master's decision and not this file's to re-take. `brand.test.ts`
 * compares what comes out of here against the master, so these numbers are
 * pinned rather than trusted.
 */
export const MARK_R = 182;
export const MARK_CIRCLES = [
  { cx: 512, cy: 396.5 },
  { cx: 626.32, cy: 594.5 },
  { cx: 397.68, cy: 594.5 },
] as const;

/** `444.32000000000005` is not a coordinate anybody wrote down. */
const n = (value: number) => String(Number(value.toFixed(4)));

/**
 * Three circles as three subpaths of one path, under `evenodd`.
 *
 * Even-odd counts crossings: a point inside one circle is odd and painted,
 * inside two is even and cut away, inside all three is odd and painted again.
 * So the three lens overlaps are holes the field shows through and the middle
 * is white — which is why this drawing needs no palette for its overlaps where
 * the pale mark needs four colours for them.
 */
export const MARK_PATH = MARK_CIRCLES.map(
  ({ cx, cy }) =>
    `M${n(cx - MARK_R)} ${n(cy)}a${MARK_R} ${MARK_R} 0 1 0 ${2 * MARK_R} 0` +
    `a${MARK_R} ${MARK_R} 0 1 0 -${2 * MARK_R} 0Z`,
).join('');

const SIZE = 1024;

const gradient = ([id, cx, cy, r, stops]: (typeof GRADIENTS)[number]) =>
  `<radialGradient id="${id}" gradientUnits="userSpaceOnUse" cx="${cx}" cy="${cy}" r="${r}">` +
  stops
    .map(
      ([offset, colour, opacity]) =>
        `<stop offset="${offset}%" stop-color="${colour}" stop-opacity="${opacity}"/>`,
    )
    .join('') +
  '</radialGradient>';

const head = (size: number) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${SIZE} ${SIZE}">`;

const DEFS = `<defs>\n${GRADIENTS.map(gradient).join('\n')}\n</defs>`;

const FIELD =
  `<rect width="${SIZE}" height="${SIZE}" fill="${FIELD_BASE}"/>\n` +
  GRADIENTS.map(([id]) => `<rect width="${SIZE}" height="${SIZE}" fill="url(#${id})"/>`).join('\n');

const MARK = `<path d="${MARK_PATH}" fill="#FFFFFF" fill-rule="evenodd"/>`;

/**
 * The field on its own, for anything drawing its own thing on top.
 *
 * The link-preview card is the only caller: it wants the icon's surface behind
 * a mark and a wordmark laid out its own way, rather than the finished square.
 */
export function fieldSvg(size: number): string {
  return `${head(size)}\n${DEFS}\n<g id="field">\n${FIELD}\n</g>\n</svg>`;
}

/**
 * The mark alone, white, on nothing — and cropped to itself.
 *
 * The icon's 1024 canvas carries a margin, because iOS rounds the corners of
 * whatever it is handed and a mark against the edge would lose its ends. Here
 * that margin is dead space inside a fixed box: the card draws this at 300px
 * beside a word, and the margin would make the mark read as smaller than the
 * word it belongs to, with a hole between them.
 *
 * Square, taking the wider of the two dimensions rather than the box, so the
 * circles stay circles — the artwork is 592.6 across and 562 tall, and
 * stretching it to fill a square is the one distortion nobody would forgive.
 */
export function symbolSvg(size: number): string {
  const xs = MARK_CIRCLES.map((c) => c.cx);
  const ys = MARK_CIRCLES.map((c) => c.cy);
  const span = Math.max(...xs) - Math.min(...xs), tall = Math.max(...ys) - Math.min(...ys);
  const box = Math.max(span, tall) + 2 * MARK_R;
  const left = (Math.min(...xs) + Math.max(...xs)) / 2 - box / 2;
  const top = (Math.min(...ys) + Math.max(...ys)) / 2 - box / 2;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" ` +
    `viewBox="${n(left)} ${n(top)} ${n(box)} ${n(box)}">\n${MARK}\n</svg>`
  );
}

/**
 * The whole icon: field, then mark.
 *
 * Full bleed and square, with no corner radius of its own — iOS masks whatever
 * it is given and rounding here would round it twice. A browser draws a favicon
 * as it arrives, so the tab gets the same square the home screen does.
 */
export function appIconSvg(size: number): string {
  return `${head(size)}\n${DEFS}\n<g id="field">\n${FIELD}\n</g>\n<g id="mark">\n${MARK}\n</g>\n</svg>`;
}
