/**
 * One logo, two drawings, and every copy of each must be the same drawing.
 *
 * **The pale mark** is coloured shapes on nothing: seven explicit fills, drawn
 * inline at 22 to 48px on a white page. It exists twice, as a React component
 * for the web and in `react-native-svg` for the phone.
 *
 * **The app icon** is the opposite claim in the same geometry — three circles
 * punched white out of a gradient field under `evenodd`, so the overlaps are
 * holes rather than colours. It exists as a master under `assets/branding`,
 * generated from three numbers; as the mirror in `appIcon.ts` that a server
 * route can actually import; as the favicon; and, through that mirror, as the
 * field and mark on the link-preview card.
 *
 * Nobody notices these drifting. Every one keeps working, every one looks like
 * the logo, and the discrepancy surfaces in a screenshot with one beside
 * another a year later. It has already happened twice, and the two failures
 * are why this file is shaped the way it is:
 *
 *   - The link-preview image had invented its own palette — three flat circles
 *     at 72% alpha in colours appearing nowhere else — under a comment saying
 *     the geometry was "the same six numbers". The geometry was; nothing else
 *     was. A link card is the one surface a developer never looks at.
 *
 *   - The website wore the pale mark in its tab while the phone wore the icon,
 *     for months, because this file had the split written down as deliberate.
 *     It *was* deliberate; what it cost was the two clients no longer looking
 *     like one product, which is the thing this file exists to prevent.
 *
 * The second is settled now, and only where the product appears as an icon:
 * the favicon and the preview card carry the app icon, and the pages still
 * carry the pale mark. So the split is still real, and what is asserted below
 * is which surfaces are on which side of it.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { MARK_CENTRES, MARK_FILLS, MARK_R } from '../app/components/Mark';
import { FIELD_BASE, GRADIENTS, MARK_PATH, appIconSvg, fieldSvg, symbolSvg } from '../src/appIcon';

const read = (path: string) =>
  readFileSync(fileURLToPath(new URL(path, import.meta.url)), 'utf8');

/* The pale master, which is still what a Parea logo *drawn on a page* is. */
const icon = read('../../../assets/branding/parea-icon.svg');
/** The dark master, generated by `scripts/build-icon.mjs` and rendered into
    the app's store assets by `apps/mobile/scripts/render-icons.mjs`. */
const appMaster = read('../../../assets/branding/parea-icon-dark-refined.svg');
const favicon = read('../app/icon.svg');
const web = read('../app/components/Mark.tsx');
/** The second copy of the pale mark: the same drawing in `react-native-svg`. */
const native = read('../../mobile/src/Mark.tsx');
const og = read('../app/api/og/route.tsx');

/** Comments out, whitespace flattened — what two SVGs have to agree on. */
const shape = (svg: string) => svg.replace(/<!--[\s\S]*?-->/g, '').replace(/\s+/g, ' ').trim();

const FILLS = Object.values(MARK_FILLS);

/** Every `<circle>` in an SVG source, as numbers. */
function circlesIn(svg: string) {
  return [...svg.matchAll(/<circle cx="(\d+)" cy="(\d+)" r="(\d+)"/g)].map((m) => ({
    cx: Number(m[1]),
    cy: Number(m[2]),
    r: Number(m[3]),
  }));
}

describe('the app icon, on the two surfaces the web wears it', () => {
  /*
   * A server route cannot read the master — it is outside `apps/web`, and a
   * deployed function gets what the bundler traced rather than what is in the
   * repository — so `appIcon.ts` mirrors it and these two assertions are what
   * make the mirror safe. Whitespace is flattened because the two are laid out
   * differently and a newline is not part of a logo; everything else, down to
   * each gradient stop's opacity, has to match.
   */
  it('is the master, mirrored into something the web can import', () => {
    expect(shape(appIconSvg(1024))).toBe(shape(appMaster));
  });

  it('is the master again in the tab, byte for byte through that mirror', () => {
    expect(shape(favicon)).toBe(shape(appMaster));
  });

  it('is the field and the mark, taken apart, on the link card', () => {
    /*
     * The card wants the icon's surface with its own layout over it — a mark
     * at its own size and a word under it — so it asks for the two halves
     * rather than the finished square. Each half has to be exactly its half of
     * the icon and nothing of the other, or the card is a third drawing again.
     */
    const field = fieldSvg(640);
    const symbol = symbolSvg(300);
    const icon640 = appIconSvg(640);

    expect(field).toContain(FIELD_BASE);
    for (const [id] of GRADIENTS) expect(field, `${id} missing from the field`).toContain(id);
    expect(field, 'the field is the surface, not the logo').not.toContain(MARK_PATH);

    expect(symbol).toContain(MARK_PATH);
    expect(symbol).toContain('fill-rule="evenodd"');
    expect(symbol, 'the mark is the logo, not the surface').not.toContain(FIELD_BASE);

    // And between them they are the icon: the halves are cut from it rather
    // than redrawn beside it.
    expect(icon640).toContain(MARK_PATH);
    for (const [id] of GRADIENTS) expect(icon640).toContain(id);

    expect(og).toMatch(/fieldSvg\(BOX\)/);
    expect(og).toMatch(/symbolSvg\(MARK\)/);
  });

  it('carries none of the pale colours', () => {
    /*
     * The two drawings say opposite things and the failure mode is one leaking
     * into the other: a pale fill turning up here means somebody has pasted the
     * page mark onto the field, where its overlaps are holes and its seven
     * colours have nothing to do.
     */
    for (const fill of FILLS) {
      expect(appIconSvg(1024), `${fill} should not be in the app icon`).not.toContain(fill);
      expect(og, `${fill} should not be on the link card`).not.toContain(fill);
    }
  });

  it('is full bleed, with no corner of its own', () => {
    // iOS masks what it is given, so a rounded source is rounded twice. A
    // browser draws a favicon as it arrives, which is why the tab can have the
    // same square the home screen does.
    expect(favicon).toMatch(/<rect width="1024" height="1024" fill="#[0-9A-F]{6}"\/>/);
    expect(favicon).not.toMatch(/\brx="/);
  });
});

/**
 * The pale master's own icon — `parea-icon.svg`, the pastel field.
 *
 * The same construction as the dark one and a generation older: a white
 * even-odd mark over a field, which is what made it the obvious thing to carry
 * into the tab once the tab stopped wearing the page mark. It is still
 * rendered and still checked, because an untested copy is how the preview
 * image came to have a palette of its own, and "it is allowed to differ" is
 * not the same claim as "it differs in these ways".
 */
describe('the pastel icon master', () => {
  it('keeps the three centres, on a radius of its own', () => {
    /*
     * The centres are the design — three points 132 from a middle at 120°
     * apart, first one straight up — and they have not moved. The radius has:
     * 200 was chosen when the mark was a small coloured shape that needed
     * every pixel of colour it could get at 16px, and here the colour is the
     * field and the circles are the absence of it, so tighter circles mean
     * less field showing and a mark that reads as one white blob with notches.
     */
    const path = icon.match(/id="mark"[\s\S]*?d="([\s\S]*?)"/)?.[1];
    expect(path, 'no path with id="mark" in the brand master').toBeDefined();

    // `M cx-r cy a r r 0 1 0 2r 0 …`, one subpath per circle.
    const subpaths = [...(path ?? '').matchAll(/M ([\d.]+) ([\d.]+) a ([\d.]+) [\d.]+/g)].map((m) => ({
      cx: Number(m[1]) + Number(m[3]),
      cy: Number(m[2]),
      r: Number(m[3]),
    }));
    expect(subpaths.length, 'the extractor found nothing, which is not a pass').toBe(3);

    /*
     * The three sit 132 from a point, 120° apart, first one straight up — the
     * design, unchanged. Where that point *is* has moved: the mark is placed
     * between the two defensible centrings rather than on the mass, so the
     * centres are 16.5 lower than the in-app mark's. Checked as a shape rather
     * than against `MARK_CENTRES`, which describes the other drawing.
     */
    const cx = subpaths.map((c) => c.cx).sort((a, b) => a - b);
    const cy = subpaths.map((c) => c.cy);
    expect(Math.round(((cx[0]! + cx[2]!) / 2) * 100) / 100).toBe(512);
    // Two low and level, one high and centred: an equilateral triangle, point up.
    expect(new Set(cy).size).toBe(2);
    const [high, low] = [Math.min(...cy), Math.max(...cy)];
    expect(low - high).toBeCloseTo(198, 0); // 1.5 × 132
    expect(cx[2]! - cx[0]!).toBeCloseTo(228.63, 1); // 2 × 132 × sin 60
    for (const circle of subpaths) expect(circle.r).toBe(180);
  });

  it('punches the circles out rather than painting seven regions', () => {
    /*
     * One path, three subpaths, `evenodd`. A region covered an odd number of
     * times is white and an even number is not painted at all, so the three
     * lenses are holes and the field shows through them — which is why no two
     * of them are the same colour and none of them had to be chosen.
     *
     * The seven explicit fills existed because the mark used to sit on white,
     * where a transparent overlap would have been white too and the lenses
     * would have vanished. There is nothing to invent on a field.
     */
    expect(icon).toMatch(/fill-rule="evenodd"/);
    expect(icon).not.toMatch(/clip-path=/);
    for (const fill of FILLS) {
      expect(icon, `${fill} should no longer be in the icon`).not.toContain(fill);
    }
  });

  it('is full bleed, with no corner of its own', () => {
    /*
     * iOS rounds the corners itself and App Store Connect rejects an alpha
     * channel. The artwork this came from was drawn with its corners already
     * rounded against black; rounding here would round them twice and put
     * black inside the mask.
     */
    /*
     * A base the field is painted over, and it is not white: the brief asks
     * for airy, and white showing through where nothing reaches full strength
     * reads as a vignette rather than as air.
     */
    expect(icon).toMatch(/<rect width="1024" height="1024" fill="#[0-9A-F]{6}"\/>/);
    expect(icon).not.toMatch(/\brx="/);
    // The corner lives in the preview and nowhere else.
    expect(read('../../../assets/branding/parea-icon-preview.svg')).toMatch(/rx="224"/);
  });

  it('names the two halves the Android layers are cut from', () => {
    // `render-icons.mjs` takes them apart by id. It used to pattern-match a
    // white fill and broke the first time this file changed.
    expect(icon).toMatch(/<g id="field">/);
    expect(icon).toMatch(/id="mark"/);
  });
});

/**
 * The native mark, which is JSX rather than an SVG document.
 *
 * Its own block because `circlesIn` cannot read it: the geometry is in the same
 * `MARK_CENTRES` literal the web component uses — `{ cx: 512, cy: 400 }` — not
 * in `<circle cx="512">`. The thing being checked is the same, and it is the
 * thing that matters: four drawings of one logo agreeing about where the
 * circles are and what colour the overlaps come out.
 */
describe('the native mark', () => {
  it('uses the same three centres and radius as the component', () => {
    const centres = [...native.matchAll(/\{ cx: (\d+), cy: (\d+) \}/g)].map((m) => ({
      cx: Number(m[1]),
      cy: Number(m[2]),
    }));
    expect(centres.length, 'the extractor found nothing, which is not a pass')
      .toBeGreaterThan(2);

    const key = ({ cx, cy }: { cx: number; cy: number }) => `${cx},${cy}`;
    expect([...new Set(centres.map(key))].sort()).toEqual([...MARK_CENTRES.map(key)].sort());
    expect(native).toMatch(new RegExp(`MARK_R = ${MARK_R}\\b`));
  });

  it('carries all seven fills', () => {
    for (const fill of FILLS) {
      expect(native, `${fill} missing`).toContain(fill);
    }
  });

  it('paints the overlaps rather than compositing them', () => {
    /*
     * No alpha on the *colours*, for the reason the other three give: multiply
     * turns the pink-over-mint lens muddy, and that lens is where the warmth
     * is. Every one of the seven is an explicit value.
     *
     * This asserted no alpha in the file at all, which was the same rule until
     * the spinner needed the mark in one colour. There, alpha is the only axis
     * left — the three circles sit on an equilateral arrangement, so a flat
     * silhouette is unchanged by a third of a turn and does not read as
     * turning. It cannot muddy anything, because there is one colour and
     * nothing for it to blend with.
     *
     * So the rule is stated where it applies: the branded mark composites
     * nothing, and the ramp exists only on the path that has no brand colours
     * in it.
     */
    expect(native).not.toMatch(/rgba\(|mixBlendMode/);
    // Drawn at full strength whenever it is drawn in its own colours.
    expect(native).toMatch(/: \{\s*pink: 1,\s*blue: 1,\s*mint: 1,/);
    expect(native).toMatch(/pinkOnBlue: 1,\s*pinkOnMint: 1,\s*blueOnMint: 1,\s*centre: 1,/);
    // And the ramp is reachable only through `tint`.
    expect(native).toMatch(/const mono = tint !== undefined;/);
    expect(native).toMatch(/clipPath=/);
  });

  it('gives each instance its own clip ids', () => {
    /*
     * `react-native-svg` does not scope `clipPath` ids per `Svg` on every
     * platform, so two marks mounted at once with hard-coded ids can clip
     * against each other's circles — which looks like one of them losing its
     * overlaps and nothing else.
     */
    expect(native).toMatch(/useId\(\)/);
    expect(native).toMatch(/\$\{id\}-blue/);
  });
});

describe('the component', () => {
  it('carries all seven fills', () => {
    for (const fill of FILLS) expect(web, `${fill} missing`).toContain(fill);
  });

  it('keeps the ratio the icon says the design depends on', () => {
    /*
     * icon.svg: "three circles of radius 200, centres 132 from a point". At
     * 0.66 the three meet in a curved triangle big enough to be a shape in its
     * own right, which is the subject. Spread them and it collapses to a
     * sliver and the mark stops meaning anything.
     *
     * It was 0.73, and tightening it is half of the answer to the mark being
     * too faint at 16 and 24px — the centre is the part carrying the meaning
     * and it needs to be a shape rather than a seam. The other half is the
     * radius and the chroma.
     */
    const [top] = MARK_CENTRES;
    const centre = { x: 512, y: 532 };
    const offset = Math.hypot(top.cx - centre.x, top.cy - centre.y);
    expect(offset / MARK_R).toBeCloseTo(0.66, 2);
  });

  it('is big enough in its own box to survive being drawn small', () => {
    // The complaint that started this: in the sidebar it almost disappeared.
    // The artwork has to occupy most of the canvas, or every size below 24px
    // is mostly margin.
    const span = 2 * (MARK_R + Math.hypot(MARK_CENTRES[0].cx - 512, MARK_CENTRES[0].cy - 532));
    expect(span / 1024).toBeGreaterThan(0.6);
    // And not so big that the app icon loses its margin, which iOS needs
    // because it rounds the corners itself.
    expect(span / 1024).toBeLessThan(0.72);
  });

  it('does not paint a background rect on the web', () => {
    // The icons need one — iOS rejects an alpha channel, and a favicon sits on
    // whatever chrome the browser draws — and the inline component must not,
    // or the mark sits in a white box on any other surface. Which is also why
    // the mark handed to the link card is `symbolSvg` and not the whole icon:
    // the card paints the field itself, at its own size.
    expect(icon).toContain('<rect width="1024" height="1024"');
    expect(favicon).toContain('<rect width="1024" height="1024"');
    expect(web).not.toContain('<rect');
    expect(symbolSvg(300)).not.toContain('<rect');
  });
});

describe('the wordmark', () => {
  const css = read('../app/globals.css');
  const rule = css.match(/\.wordmark \{[^}]*\}/)?.[0] ?? '';

  it('is set lowercase, and tracked in rather than out', () => {
    /*
     * `PAREA` at +.04em was clean and institutional — closer to an
     * architecture practice than to an app for the photographs from somebody's
     * evening — and holding the letters apart is the opposite of what the mark
     * beside it means.
     */
    expect(rule, 'the extractor found no .wordmark rule').not.toBe('');
    expect(rule).toMatch(/text-transform:\s*lowercase/);
    expect(rule).toMatch(/letter-spacing:\s*-\.02em/);
  });

  it('keeps the proper noun in the markup', () => {
    // Drawn lowercase, written as a name. A screen reader reads the DOM, and
    // the accessible name of this product is Parea.
    for (const path of ['../app/components/Rail.tsx', '../app/components/LoginScreen.tsx']) {
      expect(read(path)).toMatch(/className="wordmark[^"]*">Parea</);
    }
  });

  it('is drawn the same way in the link preview', () => {
    // The one place the wordmark is set outside this stylesheet. It said
    // `PAREA` with the letters spaced twelve pixels apart, which is where the
    // old treatment survived longest.
    expect(og).toContain('>parea<');
    expect(og).toMatch(/letterSpacing:\s*-/);
  });
});
